data:
  - 
    name: "lrv_multi"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    revision: script
  - 
    name: "llava_665k_multi"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    shuffle: true
    revision: script
  - 
    name: "dreamsim"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    revision: script
  - 
    name: "birds-to-words"    
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    revision: script
  -
    name: "spot-the-diff"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    revision: script
  - 
    name: "coinstruct"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    max_size: 100000 # 150K original
    shuffle: true
    revision: script
  - 
    name: "nlvr2"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    shuffle: true
    revision: script
  - 
    name: "iconqa"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    shuffle: true
    revision: script
  - 
    name: "contrastive_caption"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    revision: script
  - 
    name: "imagecode"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    shuffle: true
    revision: script
  - 
    name: "multi_vqa"
    type: huggingface
    path: "TIGER-Lab/Mantis-Instruct"
    format: chat
    split: train
    shuffle: true
    revision: script