train_file: ['/DATA/workshop/personal/benchmark/data/video_score_image_align_gt_Wcaption_Wpath.json',
             ]
laion_path: ''   
pretrained: '/DATA/workshop/personal/benchmark/BLIP/weights/blip/model_base.pth'
# pretrained: '/DATA/workshop/personal/benchmark/BLIP/output/Pretrain_humangt_9_true_lrlarge/checkpoint_990.pth'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0

image_size: 224
batch_size: 30

queue_size: 57600
alpha: 0.4

# optimizer
weight_decay: 0.05
# init_lr: 3e-4
# min_lr: 1e-6
# warmup_lr: 1e-6
init_lr: 3e-6
min_lr: 1e-6
warmup_lr: 1e-6
lr_decay_rate: 0.9
max_epoch: 1000
warmup_steps: 3000



