model_path: LanguageBind/Open-Sora-Plan-v1.1.0
version: 65x512x512
num_frames: 65
height: 512
width: 512
cache_dir: "./cache_dir"
text_encoder_name: DeepFloyd/t5-v1_1-xxl

prompt_path: 'prompt.txt'

ae: CausalVAEModel_4x8x8
fps: 24
guidance_scale: 7.5
num_sampling_steps: 150
enable_tiling: True