train_file: ['']
test_file: ''
laion_path: ''   
gallery: 'character/BLIP/data/gallerys.json'
query: ''

# size of vit model; base or large
vit: 'large'
vit_grad_ckpt: False
vit_ckpt_layer: 0

image_size: 224
batch_size: 500 # 75

queue_size: 57600
alpha: 0.4

# optimizer
weight_decay: 0.05
init_lr: 3e-5 #3e-4
min_lr: 1e-6
warmup_lr: 1e-6
lr_decay_rate: 0.9
max_epoch: 50 # 20
warmup_steps: 28000

# test retrieval
k_test: 10



